//
//  DeveloperPreview.swift
//  Airbnb
//
//  Created by Aime-Barca on 3/6/25.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            address: "124 Main St",
            city: "Miami",
            state: "Florida",
            title: "Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Alice Johnson",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            pricePerNight: 450,
            latitude: 27.7749,
            longitude: -82.6349,
            imageURLs: ["listing-5", "listing-6", "listing-7", "listing-8"],
            address: "45 Ocean Blvd",
            city: "Tampa",
            state: "Florida",
            title: "Beachfront Escape",
            rating: 4.75,
            features: [.selfCheckIn, .superHost],
            amenities: [.pool, .wifi, .balcony, .tv, .laundry],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "David Lee",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 300,
            latitude: 29.4241,
            longitude: -98.4936,
            imageURLs: ["listing-6", "listing-7", "listing-4", "listing-1"],
            address: "101 Downtown Ave",
            city: "San Antonio",
            state: "Texas",
            title: "Cozy Downtown Loft",
            rating: 4.9,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .balcony, .tv, .office],
            type: .townHouse
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Emily Davis",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 8,
            numberOfBeds: 5,
            pricePerNight: 750,
            latitude: 33.7490,
            longitude: -84.3880,
            imageURLs: ["listing-3", "listing-1", "listing-5", "listing-4"],
            address: "350 Park Ave",
            city: "Atlanta",
            state: "Georgia",
            title: "Luxury Mansion",
            rating: 4.85,
            features: [.selfCheckIn, .superHost],
            amenities: [.office, .wifi, .balcony, .laundry],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Chris Harris",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 180,
            latitude: 34.0522,
            longitude: -118.2437,
            imageURLs: ["listing-7", "listing-8", "listing-1", "listing-2"],
            address: "300 Sunset Blvd",
            city: "Los Angeles",
            state: "California",
            title: "Modern Studio",
            rating: 4.7,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .tv, .laundry],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Samantha Lee",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            pricePerNight: 350,
            latitude: 40.7128,
            longitude: -74.0060,
            imageURLs: ["listing-2", "listing-6", "listing-7", "listing-4"],
            address: "200 Central Park",
            city: "New York",
            state: "New York",
            title: "Central Park View",
            rating: 4.95,
            features: [.selfCheckIn, .superHost],
            amenities: [.balcony, .wifi, .tv, .laundry],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Mason Green",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 4,
            pricePerNight: 680,
            latitude: 37.7749,
            longitude: -122.4194,
            imageURLs: ["listing-5", "listing-6", "listing-7", "listing-8"],
            address: "400 Mission St",
            city: "San Francisco",
            state: "California",
            title: "Penthouse Suite",
            rating: 4.8,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .laundry, .balcony],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Olivia Brooks",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 400,
            latitude: 41.8781,
            longitude: -87.6298,
            imageURLs: ["listing-5", "listing-7", "listing-1", "listing-3"],
            address: "500 Lake Shore Dr",
            city: "Chicago",
            state: "Illinois",
            title: "Lakeview Apartment",
            rating: 4.6,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .balcony, .laundry],
            type: .apartment
        )
    ]
}
